apiVersion: v1
kind: Service
metadata:
  # This service only exists to create DNS entries for each pod in the stateful
  # set such that they can resolve each other's IP addresses. It does not
  # create a load-balanced ClusterIP and should not be used directly by clients
  # in most circumstances.
  name: scylladb-cluster
  namespace: scylladb
  labels:
    app: scylladb
    service_type: platform
    service_id: scylladb
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: scylladb