apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: scylladb
  namespace: scylladb
  labels:
    app: scylladb
    service_type: platform
    service_id: scylladb
spec:
  ports:
    - port: 9042
      name: cql
  selector:
    app: scylladb
  type: LoadBalancer